name: Run Airbnb Bot

on:
  schedule:
    - cron: '0 * * * *' # This cron expression runs the job every hour

jobs:
  run-airbnb-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python airbnb_bot2.py